### ISSUE TITLE
Create composer.json

### ISSUE THREAD

**Issue by fabiomontefuscolo** [cozy/ViewerJS#1]
Hello!

I'm a php developer and ViewerJS is a very nice library I use in some projects. If you could provide the `composer.json` for this libraries, PHP developers could keep track of your development and reference cozy/ViewerJS as a dependency available on packagist.org.

Many javascript developers make their packages available on packagist.org, for example

* https://packagist.org/packages/twbs/bootstrap
* https://packagist.org/packages/components/jquery
* https://packagist.org/packages/components/jqueryui
* https://packagist.org/packages/blueimp/jquery-file-upload
* https://packagist.org/packages/ckeditor/ckeditor
* https://packagist.org/packages/mbostock/d3
* https://packagist.org/packages/tinymce/tinymce
* https://packagist.org/packages/moment/moment
* https://packagist.org/packages/plotly/plotly.js

It would be awesome to have your package on packagist too.

**Comment by clochix** [comment]
Hello @fabiomontefuscolo,

cozy/ViewerJS is just an outdated and unmaintained fork of vandernorth/ViewerJS. You should probably submit your PR upstream.

**Comment by fabiomontefuscolo** [comment]
Hi @clochix 

Looking to the forks, this repository has the newest commit about ViewerJS. ViewerJS has no official maintainer I guess, so I did the PR in the most updated fork.

**Comment by clochix** [comment]
We have no intent to maintain this fork in the future, so what about deciding your own fork is now the most up to date version of the application, and submitting it to Packagist?
/cc @kosssi

**Comment by nono** [comment]
Sorry,  we don't intent to maintain this repository and to publish on packagist.
